# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9409553f4c4cbb424464e46c4b8bd1babe1081db3bb50ac655c6c41992aa6e61b31562bb38dd8e3ec0b1bcac7255df2c7ed7de36aac6cac5a3dff6ef96d8ba12

test:
  secret_key_base: dc6fa7b3f1030a5487d039801d955732be7acb3e228644e8be85beaff2810156bdae602f88dfe26a07a1bf14eb9da2331e1d673feb6b3ac68e103d227976483b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
